Run all tests before making a release
we removed make_release test because we'd end up with recursive
releasing

diff --git a/make_release b/make_release
--- a/make_release
+++ b/make_release
@@ -28,6 +28,14 @@ if [ ! -e "$dfile" ];  then
 fi
 echo "Created: $dfile"
 
+echo "Running tests before finalizing release"
+REVIEW_LOGLEVEL=error src/test/run-tests.py
+if [ $? -ne 0 ]; then
+    echo "Some tests failed. Review test logs and fix all problems"
+    echo "before doing a release. Aborting"
+    exit 1
+fi
+
 [ "$1" = '-b' ] && exit 0
 
 read -i 'n' -e -p "Do you want to upload file $dfile to fedorahosted? (y/n): "
